### ISSUE TITLE
请问此项目能改用ansible+BMC的方式吗

### ISSUE THREAD

**Issue by wangzheny** [voilet/cmdb#10]
项目中的salt+zabbix能换成ansible+BMC吗

**Comment by voilet** [comment]
当然可以，只要自己封装一下api就可以了，我只是提供了一个简单的框架，可以自己二次开发

**Comment by getway** [comment]
我也想改成ansible的方式，有时间交流一下嘛

**Comment by voilet** [comment]
把slat api重写一下就可以了
