### ISSUE TITLE
nginx访问 502

### ISSUE THREAD

**Issue by opser-gavin** [voilet/cmdb#11]
根据doc/htlp.txt 进行配置，到最后 uwsgi启来 nginx启来， 访问nginx 502 ，啥情况？ 求解
nginx访问时报错：
2017/02/13 10:56:03 [error] 2227#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.147.1, server: 192.168.147.128, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8100", host: "192.168.147.128", referrer: "http://192.168.147.128/"
2017/02/13 10:56:03 [error] 2227#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.147.1, server: 192.168.147.128, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8100", host: "192.168.147.128"
2017/02/13 10:56:03 [error] 2227#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 192.168.147.1, server: 192.168.147.128, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8100", host: "192.168.147.128", referrer: "http://192.168.147.128/"
2017/02/13 10:58:34 [error] 2227#0: *14 upstream prematurely closed connection while reading response header from upstream, client: 192.168.147.1, server: 192.168.147.128, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8100", host: "192.168.147.128"
2017/02/13 10:58:34 [error] 2227#0: *14 upstream prematurely closed connection while reading response header from upstream, client: 192.168.147.1, server: 192.168.147.128, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8100", host: "192.168.147.128", referrer: "http://192.168.147.128/"

**Comment by voilet** [comment]
先手动测试下程序是否有其它项未配
python manager runserver 0.0.0.0:8000
访问服务器ip:8000如访问无异常，则需要你检查uwsgi的配置
这个配置方法非常多，可自行google解决

**Comment by wenchangming211** [comment]
我的Nginx和uwsgi都启动了，浏览器访问也报502！
[root@cmdb logs]# tail -f error.log 
2017/06/15 20:23:56 [error] 4229#0: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.111.1, server: 192.168.111.134, request: "GET / HTTP/1.1", ups
tream: "uwsgi://127.0.0.1:9090", host: "192.168.111.134"2017/06/15 20:23:56 [error] 4229#0: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.111.1, server: 192.168.111.134, request: "GET /favicon.ico HTT
P/1.1", upstream: "uwsgi://127.0.0.1:9090", host: "192.168.111.134", referrer: "http://192.168.111.134/"2017/06/15 20:23:59 [error] 4229#0: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.111.1, server: 192.168.111.134, request: "GET / HTTP/1.1", ups
tream: "uwsgi://127.0.0.1:9090", host: "192.168.111.134"2017/06/15 20:23:59 [error] 4229#0: *46 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.111.1, server: 192.168.111.134, request: "GET /favicon.ico HTT
P/1.1", upstream: "uwsgi://127.0.0.1:9090", host: "192.168.111.134", referrer: "http://192.168.111.134/"
