### ISSUE TITLE
请教下salt-api、yalm这类需求的版本是多少？

### ISSUE THREAD

**Issue by chenshaorong** [voilet/cmdb#16]
我在CentOS7.3上部署了这套(Python: 2.7.5)，pip list后主要的版本如下：
    - Jinja2           2.7.2
    - PyYAML       3.10
    - salt               2015.5.10
    - uWSGI          2.0.14

salt-api本地用curl测试过是ok的，也按照流程创了一套下来没什么问题，但是点salt认证管理的时候报：
  ParserError at /salt/key_list/
expected '<document start>', but found '<block mapping start>'
  in "<unicode string>", line 9, column 9:
......

感觉有可能和yaml的版本有关系，所以想问下这套要求的yaml版本应该是多少？
或者还有其他地方需要注意的吗？

**Comment by chenshaorong** [comment]
在仪表盘那里批量执行命令是ok的（里面有其他机器），但就是系统管理->salt认证管理那块会报错，请问我应该排查哪些方面？

**Comment by voilet** [comment]
salt认证这块这几天我找个时间把有一个方法重写下就好了
那块写公用方法的时候有一个bug,后来没改

**Comment by chenshaorong** [comment]
好 那麻烦了
