### ISSUE TITLE
requests.packages.urllib3.disable_warnings()， requests模块中没有packages 这个包啊

### ISSUE THREAD

**Issue by up-up** [voilet/cmdb#2]
这是错误信息：
AttributeError at /
'module' object has no attribute 'packages'
Request Method:	GET
Request URL:	http://cmdb.surfo.com/
Django Version:	1.7.4
Exception Type:	AttributeError
Exception Value:	
'module' object has no attribute 'packages'
Exception Location:	./salt_ui/api/salt_https_api.py in <module>, line 17
Python Executable:	/usr/bin/uwsgi
Python Version:	2.7.6

这个截图是requests的版本，请问如何解决？
![image](https://cloud.githubusercontent.com/assets/10647564/17771009/849df84c-6573-11e6-9a49-21ed509d990f.png)

**Comment by voilet** [comment]
我在mac下开发的，这个可以注掉
