### ISSUE TITLE
怎么创建新账号，创建新的账号时，默认密码是什么？

### ISSUE THREAD

**Issue by guangzhimen** [voilet/cmdb#25]
我使用用户管理标签里面的"添加用户"，添加新账号，但是密码不知道在哪创建（有默认密码嘛？）
在创建用户时，"用户登录key"有什么作用？

**Comment by voilet** [comment]
如果你配置好发送邮件的邮箱，会自动给用户发送一条添加密码的链接，用户就可以使用此密码进行登录了，不用管理员给用户设置认密码
