### ISSUE TITLE
cmdb关联zabbix一些问题

### ISSUE THREAD

**Issue by VictorLee0321** [voilet/cmdb#3]
请问搭建好和配置好setting.py的zabbix地址账号密码后，为什么还是没有zabbix信息呢？谢谢，非常感谢！

**Comment by voilet** [comment]
zabbix有一个配置文件，改为True后，添加主机才会通过API通知zabbix添加监控项，另外zabbix只支持 2x版本

**Comment by VictorLee0321** [comment]
非常感谢收到您的回信，多谢指点。

现在又遇到一个问题了，我打开“ip列表”的时候，提示：

###


  Page not found (404)

Request Method: 	GET
Request URL: 	http://IP:Port/assets/ip_list/

No IDC matches the given query.

You're seeing this error because you have |DEBUG = True| in your Django 
settings file. Change that to |False|, and Django will display a 
standard 404 page.

###
这个是您写的代码路径和我配置的不对还是？我相应地看了一下“机房列表”是可以的，不知道怎么解决ip列表这个问题。

真的很高兴收到回信，我是运维实习生，公司让我按照您github上面的搭建cmdb，遇到问题网上解决不了，只能打扰作者您了，谢谢

**Comment by leemon9527** [comment]
No IDC matches the given query.
添加IDC，在操作之前请认真阅读README.md

**Comment by voilet** [comment]
ip列表这个代码里面有一个写死的地方，所以我还需要改改，开发这个功能的目的就是扫描这个要房指定的ip段，还有多少ip是可用的，一般不建意使用，因为nmap使用的是多进程，会产生大量的arp广播，交换机CPU会直接上升到90%左右

**Comment by VictorLee0321** [comment]
eben，非常感谢，多谢您这段时间的帮助，蟹蟹


来自 魅蓝 note 2

-------- 原始邮件 --------
发件人：voilet <notifications@github.com>
时间：周五 10月28日 15:00
收件人：voilet/cmdb <cmdb@noreply.github.com>
抄送：victor <victorlee0321@163.com>,Author <author@noreply.github.com>
主题：Re: [voilet/cmdb] cmdb关联zabbix一些问题 (#3)

**Comment by zhxiaohe** [comment]
请问zabbix什么时候支持3.x版本？

**Comment by voilet** [comment]
目前没有计划
