### ISSUE TITLE
安装问题请教

### ISSUE THREAD

**Issue by yuedingwangji** [voilet/cmdb#44]
大神你好，按照帮助文档，搭建的时候，打开web 界面提示 500 Internat error 
，我看了一下配置
location /static/admin {
        alias /usr/local/python2.7/lib/python2.7/site-packages/django/contrib/admin/static/admin;
 这里  /usr/local/python2.7/lib/python2.7/site-packages/django/contrib/admin/static/admin;  这里目录
在机器上没找到
 location  /static/ueditor {
        expires 30d;
        alias /data/cmdb/DjangoUeditor/static/ueditor;
还有这里，这个 /data/cmdb/DjangoUeditor/static/ueditor 目录也没找到。
不知道跟这个有没有关系，能提供一下排查思路么？
另外，我看mysites 下的 setting.py 有管理zabbix 和salt的  prod.py 也有关联zabbix 和 salt的，
那个配置是对的，zabbix api 调用，url 应该填zabbix的 api 接口地址还是 zabbix web 访问的地址，
另外salt_cdn_url , salt_center_url 这2个是干嘛的 ，该怎么填写

**Comment by voilet** [comment]
这段配置需要你自己去修改的，我的python安装在这个位置，不知道你的python安装在什么位置，自己服务器上搜索一下就可以了

联动zabbix是填写zabbix的帐号密码
salt_cdn_url这个是以前项目中用的，应该清除掉配置，只是代码还没做清除，不影响使用

**Comment by yuedingwangji** [comment]
启动uwsgi的时候报错如下
root@bdwaf:/usr/lib/x86_64-linux-gnu# /etc/init.d/uwsgi start
Starting uwsgi: 
/usr/bin/uwsgi: /usr/lib/x86_64-linux-gnu/libxml2.so.2: no version information available (required by /usr/bin/uwsgi)
/usr/bin/uwsgi: /usr/lib/x86_64-linux-gnu/libxml2.so.2: no version information available (required by /usr/bin/uwsgi)
[uWSGI] getting INI configuration from /home/hui/uwsgi/mysite_uwsgi.ini
open("/home/hui/uwsgi/mysite_uwsgi.ini"): No such file or directory [utils.c line 2162]


前面 libxml2 问题的话 ，上网找了下，应该是库文件的版本不对，明天问一下开发，请问一下 
open("/home/hui/uwsgi/mysite_uwsgi.ini"): No such file or directory [utils.c line 2162]
这个报错 要怎么解决，有什么思路

**Comment by voilet** [comment]
uwsgi /home/hui/uwsgi/mysite_uwsgi.ini 直接手动执行看是否报错？

**Comment by yuedingwangji** [comment]
之前是配置路径写错了；更正后启动提示如下
root@bdwaf:/etc/nginx/sites-enabled# /etc/init.d/uwsgi start
Starting uwsgi: 
/usr/bin/uwsgi: /usr/lib/x86_64-linux-gnu/libxml2.so.2: no version information available (required by /usr/bin/uwsgi)
/usr/bin/uwsgi: /usr/lib/x86_64-linux-gnu/libxml2.so.2: no version information available (required by /usr/bin/uwsgi)
[uWSGI] getting INI configuration from /home/hui/cmdb-master/mysite_uwsgi.ini
unlink(): No such file or directory [uwsgi.c line 959]
status 看是正常的
root@bdwaf:/etc/nginx/sites-enabled# /etc/init.d/uwsgi status
Status uwsgi: 
root     14898  0.0  0.0  84520  1524 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14900  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14901  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14903  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14904  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14905  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14907  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14908  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14909  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14910  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     14911  0.0  0.0  84520   876 ?        S    22:19   0:00 /usr/bin/uwsgi /home/hui/cmdb-master/mysite_uwsgi.ini
root     20921  0.0  0.0   9804   932 pts/26   S+   22:20   0:00 grep /usr/bin/uwsgi

nginx 配置如下：
server {
        listen 22280;
        server_name cmdb.com;
        proxy_buffer_size 64k;
        proxy_buffers   32 32k;
        proxy_busy_buffers_size 128k;

        access_log /var/log/nginx/cmdb_access.log;
        error_log /var/log/nginx/cmdb_error.log debug;

        location /static {
            alias /home/hui/cmdb-master/static;
        }   
        location /static/admin {
        alias /usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin;
        }   
        location  /static/ueditor {
        expires 30d;
        alias  /home/hui/cmdb-master/DjangoUeditor/static/ueditor;
        }   
        location / { 
                include uwsgi_params;
                #uwsgi_pass 127.0.0.1:8100;
                uwsgi_pass unix:///var/run/uwsgi.sock;
        }   

}

/home/hui/cmdb-master/mysite_uwsgi.ini 配置如下
[uwsgi]

chdir           = /home/hui/cmdb-master/
module          = mysite.wsgi
# the virtualenv (full path)
#home            = /home/web_root/cmdb/mysite

# process-related settings
# master
master          = true
# maximum number of worker processes
processes       = 10
# the socket (use the full path to be safe
#socket          = 127.0.0.1:8100
socket          = /var/run/uwsgi.sock
# ... with appropriate permissions - may be needed
# chmod-socket    = 664
# clear environment on exit
vacuum          = true
max-requests    = 5000
pidfile     = /home/hui/cmdb-master/mysite.pid

daemonize   = /tmp/cmdb.log

 访问 127.0.0.1:22280 后浏览器显示
502 网关超时；
curl 访问如下
* Rebuilt URL to: 127.0.0.1:22280/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 22280 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:22280
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< Server: BDWAF/1.0
< Date: Wed, 22 Nov 2017 14:22:45 GMT
< Content-Type: text/html; charset=utf-8,gbk
< Content-Length: 215
< Connection: keep-alive
< 
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>BDWAF/1.0</center>
<hr><center>http://www.bluedon.com</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact

nginx 错误日志如下
2017/11/22 22:11:12 [info] 14698#0: *27046 client 172.16.2.107 closed keepalive connection
2017/11/22 22:13:16 [error] 41389#0: *27132 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: cmdb.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi.sock:", host: "127.0.0.1:22280"
2017/11/22 22:13:16 [info] 41389#0: *27132 client 127.0.0.1 closed keepalive connection
2017/11/22 22:13:19 [error] 41389#0: *27135 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: cmdb.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi.sock:", host: "127.0.0.1:22280"
2017/11/22 22:13:19 [info] 41389#0: *27135 client 127.0.0.1 closed keepalive connection
2017/11/22 22:13:20 [error] 41389#0: *27137 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: cmdb.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi.sock:", host: "127.0.0.1:22280"
2017/11/22 22:13:20 [info] 41389#0: *27137 client 127.0.0.1 closed keepalive connection
2017/11/22 22:21:54 [error] 41389#0: *27500 upstream prematurely closed connection while reading response header from upstream, client: 172.16.4.95, server: cmdb.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi.sock:", host: "172.16.2.107:22280"
2017/11/22 22:22:04 [info] 41389#0: *27501 client closed connection while waiting for request, client: 172.16.4.95, server: 0.0.0.0:22280
2017/11/22 22:22:04 [info] 41389#0: *27502 client closed connection while waiting for request, client: 172.16.4.95, server: 0.0.0.0:22280
2017/11/22 22:22:04 [info] 41389#0: *27500 client 172.16.4.95 closed keepalive connection
2017/11/22 22:22:45 [error] 41389#0: *27540 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: cmdb.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///var/run/uwsgi.sock:", host: "127.0.0.1:22280"
2017/11/22 22:22:45 [info] 41389#0: *27540 client 127.0.0.1 closed keepalive connection

不知道那里错了， 网管超时应该是uwsgi 这块有问题，但不知道错在那里
