### ISSUE TITLE
uwsgi相关问题

### ISSUE THREAD

**Issue by allencct1029** [voilet/cmdb#47]
本地起了uwsgi服务之后没有报错，但是查看监听端口的时候出现这样的情况：
tcp    LISTEN     0      100    127.0.0.1:8100                  *:*                   users:(("uwsgi",pid=70675,fd=3),("uwsgi",pid=70674,fd=3),("uwsgi",pid=70673,fd=3),("uwsgi",pid=70672,fd=3),("uwsgi",pid=70671,fd=3),("uwsgi",pid=70670,fd=3),("uwsgi",pid=70669,fd=3),("uwsgi",pid=70668,fd=3),("uwsgi",pid=70667,fd=3),("uwsgi",pid=70666,fd=3),("uwsgi",pid=70665,fd=3))
打开网页无法显示，telnet8100端口也不通。
请问大神，有解决办法吗？

**Comment by voilet** [comment]
uwsgi启动后，是不能直接访问8100端口的，需要通过nginx代理到后端进行访问

**Comment by allencct1029** [comment]
是我uwsgi配置错误了 把socket改成http就可以了。现在我遇到的问题是打开web页面无法加载css还有图片这些，调试台里面显示not found 404。只看的到web框架，其他都是加载不了。

**Comment by voilet** [comment]
你可以最简单的方式先调试下
python manage.py runserver 0.0.0.0:8000
先把流程跑通在研究uwsgi吧
