### ISSUE TITLE
第2条语句导入报错

### ISSUE THREAD

**Issue by 502155589** [voilet/cmdb#50]
INSERT INTO `users_customuser` VALUES (1,'pbkdf2_sha256$15000$uM1f5HMxHOqE$zPzKtNJMheQe62Q592V5l0m60nq/5Vj4rgzlVf5nXYs=','2016-01-14 18:16:27',1,'voilet@qq.com','admin','','','','04j4wtqxhtzts642w783nfukepx0w5jc',NULL,1,0,'3eceb1e9-df90-38ed-9960-03183bc85cce',0,1,'2015-12-29 14:05:50',NULL);

**Comment by 502155589** [comment]
可以登陆进去了，但是对代码业务逻辑还要好好向大神学习

**Comment by Fistw** [comment]
我也是出错，怎么解决的？
