### ISSUE TITLE
我想问一下通过什么模式控制主机的？

### ISSUE THREAD

**Issue by 356082462** [voilet/cmdb#7]
是通过agent方式，还是通过vm或者open stack提供的api？
如果是agent方式，是不是能够做到自动发现？
如果是虚拟化平台提供的api，能够做到虚拟机的自动创建、配置、销毁？

**Comment by voilet** [comment]
我是用saltstack来对主机进行控制的

**Comment by 356082462** [comment]
系统有没有大规模使用？

**Comment by voilet** [comment]
我们线上1000+在使用
