### ISSUE TITLE
服务器授权

### ISSUE THREAD

**Issue by justinmjc** [voilet/cmdb#74]
服务器授权，这一块目前是个空壳吗？ 我给一个用户授权7台服务中的三台，但是这个用户在资产管理可以管理所有七台服务器，所以，，不太清楚，服务器授权的具体作用，麻烦解答一下，感谢！

**Comment by voilet** [comment]
这个功能写的比较鸡肋，动作太麻烦，还要用到rabbitmq,所以相应的方法就没放在代码中
近期会开源golang写的gcmdb和配套的堡垒机系统

**Comment by justinmjc** [comment]
> 这个功能写的比较鸡肋，动作太麻烦，还要用到rabbitmq,所以相应的方法就没放在代码中
> 近期会开源golang写的gcmdb和配套的堡垒机系统

awesome! 我们本来还打算写个go版的，您这边已经先行了，赞！
