### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by X-Mars** [voilet/cmdb#8]
1.  修改admin用户密码
旧密码为Admin_147258 ，输入旧密码会提示“密码由6-16位数字、字母组成",应该是前端正则要改下
2. 新建用户发送邮件
cmdb/accounts/views.py
这个文件里面写死了from email，smtp发送的时候，会被163挡回来：SMTPSenderRefused: (553, 'Mail from must equal authorized user', u'=?utf-8?b?6L+Q57u06Ieq5Yqo5YyW?= <devops@funshion.net>')

**Comment by voilet** [comment]
注意，这里代码中有一个devops@funshion.net的发件人，代码写死的，这块没改，所以需要你自己改一下

**Comment by X-Mars** [comment]
我的意思建议你写活
