### ISSUE TITLE
No module named _ssl 错误

### ISSUE THREAD

**Issue by winter13292** [voilet/cmdb#9]
Python2.7.9 
配置后一直报错-------如下------请教各位
mportError at /

No module named _ssl

Request Method: 	GET
Request URL: 	http://192.168.253.134/
Django Version: 	1.7.4
Exception Type: 	ImportError
Exception Value: 	

No module named _ssl

Exception Location: 	/usr/local/python27/lib/python2.7/ssl.py in <module>, line 97
Python Executable: 	/usr/bin/uwsgi
Python Version: 	2.7.9
Python Path: 	

['.',
 '/data/cmdb',
 '/usr/local/python27/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg',
 '/usr/local/python27/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg',
 '/usr/local/python27/lib/python27.zip',
 '/usr/local/python27/lib/python2.7',
 '/usr/local/python27/lib/python2.7/plat-linux2',
 '/usr/local/python27/lib/python2.7/lib-tk',
 '/usr/local/python27/lib/python2.7/lib-old',
 '/usr/local/python27/lib/python2.7/lib-dynload',
 '/usr/local/python27/lib/python2.7/site-packages']

Server time: 	星期二, 24 一月 2017 17:06:47 +0800

**Comment by winter13292** [comment]
通过python 命令引入 import _ssl  却不会报错

**Comment by voilet** [comment]
mac 下开发的，这一段在linux平台可以删除掉
